import { useCallback, useEffect, useState } from 'react';
import { Plus, Search } from 'lucide-react';
import { agentAPI } from '../../api/endpoints';
import PageHeader from '../../components/common/PageHeader';
import DataTable from '../../components/common/DataTable';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { toast } from '../../components/ui/toast';

const empty = { type: 'MANAGED_AGENT', displayName: '', agencyName: '', contactPerson: '', email: '', phone: '', whatsapp: '', address: '', notes: '' };
export default function Agents() {
  const [rows,setRows]=useState([]), [pagination,setPagination]=useState(null), [page,setPage]=useState(1), [search,setSearch]=useState(''), [type,setType]=useState(''), [status,setStatus]=useState('ACTIVE'), [loading,setLoading]=useState(true), [open,setOpen]=useState(false), [form,setForm]=useState(empty);
  const load=useCallback(()=>{setLoading(true);agentAPI.list({page,limit:15,search:search||undefined,type:type||undefined,status:status||undefined}).then(r=>{setRows(r.data.data||[]);setPagination(r.data.pagination)}).catch(()=>toast.error('Failed to load agents')).finally(()=>setLoading(false));},[page,search,type,status]);
  useEffect(load,[load]);
  const create=async()=>{try{await agentAPI.create(form);toast.success('Agent created');setOpen(false);setForm(empty);load();}catch(e){toast.error(e.response?.data?.message||'Failed to create agent')}};
  const columns=[{key:'displayName',label:'Agent',render:(v,r)=><div><p className="font-medium">{v}</p><p className="text-xs text-muted-foreground">{r.agencyName||r.email||r.phone||'—'}</p></div>},{key:'type',label:'Type',render:v=><span className="rounded bg-primary/10 px-2 py-1 text-xs text-primary">{v.replaceAll('_',' ')}</span>},{key:'assignedInternalStaff',label:'Assigned Staff',render:v=>v?`${v.firstName} ${v.lastName}`:'—'},{key:'_count',label:'Students / Commissions',render:v=>`${v?.students||0} / ${v?.commissions||0}`},{key:'status',label:'Status'},{key:'id',label:'',render:(id,r)=><Button size="sm" variant="outline" onClick={async()=>{await agentAPI.setStatus(id,r.status==='ACTIVE'?'INACTIVE':'ACTIVE');load()}}>{r.status==='ACTIVE'?'Deactivate':'Activate'}</Button>}];
  return <div className="space-y-6"><PageHeader title="Agents" description="Manage registered agents, managed agents, and referral partners." actions={<Button onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/>Add Agent</Button>}/><div className="flex flex-wrap gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search agents..."/></div><select className="rounded-md border border-input bg-background px-3 text-sm" value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option><option value="REGISTERED_AGENT">Registered Agent</option><option value="MANAGED_AGENT">Managed Agent</option><option value="REFERRAL_PARTNER">Referral Partner</option></select><select className="rounded-md border border-input bg-background px-3 text-sm" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select></div><DataTable columns={columns} data={rows} loading={loading} pagination={pagination} onPageChange={setPage} emptyMessage="No agents found."/>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><Card className="w-full max-w-xl"><CardHeader><CardTitle>Add Agent</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3"><select className="col-span-2 rounded-md border border-input bg-background p-2" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="REGISTERED_AGENT">Registered Agent</option><option value="MANAGED_AGENT">Managed Agent</option><option value="REFERRAL_PARTNER">Referral Partner</option></select>{Object.keys(empty).filter(k=>k!=='type').map(k=><Input key={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={k.replace(/([A-Z])/g,' $1')}/>) }<div className="col-span-2 flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={create}>Create</Button></div></CardContent></Card></div>}</div>;
}
