const ALFA_INTAKES_2026 = [
  'January 2026',
  'February 2026',
  'March 2026',
  'April 2026',
  'May 2026',
  'June 2026',
  'July 2026',
  'August 2026',
  'September 2026',
  'October 2026',
  'November 2026',
  'December 2026',
];

const ALFA_PROGRAMMES = [
  { level: 'Foundation', name: 'Foundation in Business' },
  { level: 'Foundation', name: 'Foundation in Arts and Design' },

  { level: 'Diploma', name: 'Diploma in Accountancy' },
  { level: 'Diploma', name: 'Diploma in Business Administration' },
  { level: 'Diploma', name: 'Diploma in E-Business' },
  { level: 'Diploma', name: 'Diploma in Information Technology' },
  { level: 'Diploma', name: 'Diploma in Retail Management (WBL)' },
  { level: 'Diploma', name: 'Diploma in Law Enforcement' },
  { level: 'Diploma', name: 'Diploma in Early Childhood' },
  { level: 'Diploma', name: 'Diploma in Early Childhood (ODL)' },
  { level: 'Diploma', name: 'Diploma in Teaching of English as a Second Language (TESL)' },
  { level: 'Diploma', name: 'Diploma in Graphic Design' },
  { level: 'Diploma', name: 'Diploma in Multimedia Design' },
  { level: 'Diploma', name: 'Diploma in Architecture' },
  { level: 'Diploma', name: 'Diploma in Interior Design' },
  { level: 'Diploma', name: 'Diploma in Culinary Arts' },
  { level: 'Diploma', name: 'Diploma in Tourism Management' },
  { level: 'Diploma', name: 'Diploma in Tourism Hajj and Umrah (WBL)' },
  { level: 'Diploma', name: 'Diploma in Hotel Management (WBL)' },
  { level: 'Diploma', name: 'Diploma in Event Management' },
  { level: 'Diploma', name: 'Diploma in Health Care Management' },
  { level: 'Diploma', name: 'Diploma in Pharmacy' },

  { level: 'Bachelor', name: 'Bachelor of Arts (HONOURS) Business Administration' },
  { level: 'Bachelor', name: 'Bachelor of Arts (HONOURS) Business Administration (ODL)' },
  { level: 'Bachelor', name: 'Bachelor of E-Business (HONOURS)' },
  { level: 'Bachelor', name: 'Bachelor (HONOURS) Human Resource Management' },
  { level: 'Bachelor', name: 'Bachelor of Information Technology (HONOURS)' },
  { level: 'Bachelor', name: 'Bachelor of Law Enforcement' },
  { level: 'Bachelor', name: 'Bachelor in Computer Science (Cyber Security and Networks)' },
  { level: 'Bachelor', name: 'Bachelor Artificial Intelligence' },
  { level: 'Bachelor', name: 'Bachelor in Accounting and Finance (HONOURS)' },
  { level: 'Bachelor', name: 'Bachelor of Arts (HONOURS) Graphic Design' },
  { level: 'Bachelor', name: 'Bachelor of Arts (HONOURS) Creative Multimedia' },
  { level: 'Bachelor', name: 'Bachelor of Science (HONOURS) in Hospitality Management' },
  { level: 'Bachelor', name: 'Bachelor of Early Childhood Education (HONOURS)' },
  { level: 'Bachelor', name: 'Bachelor of Science (HONOURS) in Architecture' },

  { level: 'Master', name: 'Master of Business Administration (Coursework)' },
  { level: 'Master', name: 'Master of Business Administration (ODL) (Coursework)' },
  { level: 'Master', name: 'Master of Business Administration (International Business) (Coursework)' },
  { level: 'Master', name: 'Master of Project Management (Coursework)' },
  { level: 'Master', name: 'Master in Information Technology (Coursework)' },
  { level: 'Master', name: 'Master of Education in Early Childhood Education (Research)' },
  { level: 'Master', name: 'Master of Education in TESL (Research)' },
  { level: 'Master', name: 'Master of Science in Management (Research)' },
  { level: 'Master', name: 'Master in Art and Design (Research)' },
  { level: 'Master', name: 'Master in Education (Research)' },
  { level: 'Master', name: 'Master of Philosophy in Engineering (Research)' },
  { level: 'Master', name: 'Master in Supply Chain Management (Coursework)' },
  { level: 'Master', name: 'MBA in Oil and Gas Management (Coursework)' },
  { level: 'Master', name: 'Master of Music (Research)' },
  { level: 'Master', name: 'Master of Mechanical Engineering (Coursework)' },

  { level: 'PhD', name: 'Doctor of Philosophy in Management' },
  { level: 'PhD', name: 'Doctor of Philosophy in Social Sciences' },
  { level: 'PhD', name: 'Doctor of Philosophy in Information Technology' },
  { level: 'PhD', name: 'Doctor of Philosophy in Education' },
  { level: 'PhD', name: 'Doctor of Philosophy in Art and Design' },
  { level: 'PhD', name: 'Doctor of Philosophy in Performing Art' },
  { level: 'PhD', name: 'Doctor of Philosophy in Sport Science' },
  { level: 'PhD', name: 'Doctor of Business Administration (DBA)' },
];

function isAlfaUniversityName(name) {
  return /alfa university college/i.test(String(name || ''));
}

module.exports = {
  ALFA_INTAKES_2026,
  ALFA_PROGRAMMES,
  isAlfaUniversityName,
};
